package backend;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import javax.ejb.Stateless;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

@Stateless
@Path("echo")
public class EchoBean {

	@GET
	@Path("{something}")
	public String echo(@PathParam("something")String echoText) {
		
		String buildId = null;
		try (BufferedReader br=new BufferedReader(new InputStreamReader(getClass().getResourceAsStream("/META-INF/build_id.txt")))) {
			buildId = br.readLine();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
				
		return "Echo " + echoText + "\n" + "Generated by build: " + buildId;
	}

}
